spring.application.name=loja_virtual_mentoria

spring.datasource.url=jdbc:postgresql://localhost:5432/loja_virtual_mentoria
spring.datasource.username=postgres
spring.datasource.password=12345678

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

spring.datasource.plataform=postgres